[GOOGLE_SHEETS_CREDS]
type = "service_account"
project_id = "netflix-recommendation-system"
private_key_id = "19d21e28b1f49ff2df5a643be8b798e02c0b4427"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjzqCQXarWf2GO
we/YwND/ocZFTPwhP5Q9cupVQk4eb+6GsXscO1yUtic6tyGC/dRoE8AV0qNlDbYU
GngmMuzEbYvOyUz0agndVa1fBdud1eS33TaSDreQ8ifc00QE8ckSzZknlStOAXZj
aylZvqMYmbKyUpI2u/w/zfKa+WBfaW52s7vcT8uTZe4SElEPknfAc2alIX8kCETC
EMhJG1SP3AjMuP87fVQHKfIn3xMNXUddChfrXGxCWOb+WJke8HXyZ4KuaoT+UvwW
gsp6JqcPyn8mZrtsIZ3kjWhQNOxxoe4p4mW0tGk/HDQwdebaBq3i/nNCVOZi5cMb
z6tTHmyXAgMBAAECggEAKsftkF7+y7xtQkV6eO6w8Sjc1rvf55CMksOnbS6ABChK
F6Jx97nQJ59Tm6uzj+mCP69h1ddSVxJtnLXh1W6f1z2pUUKtgIL/akECR4OOnEQE
aWESM/iukXpgcRB9yB3uAGl69xuE3+fXZ1FDGTb7Yw3OKL3n9n50Hzlac68cYZ5M
663AOf0Ucmb76lojd0ZblYSxrwOxzIF16aE4M+PSG0RtZqwWPGA5MEa18XNmwe+/
H9eM/kMB6mhGXRdeSBmP/IkJMphemln3tkdy9rrJG9or38/NOkrswkVZjO+Nw5da
Xz50VbtIyPDj+Ei2iIk6Xk0ZfuLxb6tsJZnEeMT2yQKBgQDyRrV0p18yADSlgkGk
ATXDU1ij3cxkrUVasUeJEp2AN5pPFJKWAIwQMiewPdMPEQiB0VqOavM9mgGN4fDi
mwyHe4yglRX/MEvmd6L64XbU9rUAXopkWYvjrkfD1+Zl/krpUYO5NxFeSO2LACrA
YSidt38d6kSTXFziXzDmIElwiQKBgQDwthmMoh/xWktu6RwctsviraRkdIoN8scm
HT4l8taFqmrVdFoEwUrnErG8H4nHyFHhEAjWGkqqG/oFlGMRFJn5YeXxsktbI4P6
izmZ0umA3ATPBLAGMu/FW13+MlUQD/7A5h9Ydsfb6sJdqLaWd1/xP+c25IJDBG/R
Osv3yMBsHwKBgQDmAqFE5Z2n77ALrbU5yfhLvzX5JJpmvmWIq6PZi7XBw4gZKdPc
2xoeSi+Jz7gvpqEn9iT97qWNR0fQdr/lswPbID2rOr8ObcCxRcWSXzkdCDdg6WCD
0svPVWdGlBNlo11lUwE2dwRjOeNjQr5TtCoGSe5B7WY7bMW2GF9pKx/t2QKBgQDI
kfOYCz8yjFpugC68flRE/QsN6U1fcfwe9h7i4AWAOw/p7JlVfPo8sIcIif70SSZw
sjuqqx2rwMQEAjDJ+rCR69D+I+JGfsFp8rh8RBHtHWekV/OUNr0zZX5cYPQf/jP3
58gWnmLKDEMIZ5w8pBt9mhG+24ju7rN9U9DBFrW/YQKBgCuswlUArgnkpNdlOSce
G8w2l2nVC7PrmauUT/smQxOkg4/TWs2aJ1LJjX3Bd08HJ4wX0mHzSH24x+rZ/60x
nyWL3Fa3GVKVSKCc8EJ12dhjMmT3I/A3kY1msvasvHRvaU02C0NYPLsAnfFiNbvE
pxJReib69xE+55SDC+eVDGoS
-----END PRIVATE KEY-----
"""
client_email = "google-sheets-access@netflix-recommendation-system.iam.gserviceaccount.com"
client_id = "116827777473172720041"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/google-sheets-access%40netflix-recommendation-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
#A
